---

**`.github/workflows/GYMAIEngine.yml`**

```yaml
name: GYMAIEngine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Backend Build & Test
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Test backend
        working-directory: ./backend
        run: npm test

      # Frontend Build & Test
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

  dockerize:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push backend image
      - name: Build backend image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/chatbot-backend:latest ./backend

      - name: Push backend image
        run: docker push ghcr.io/${{ github.repository_owner }}/chatbot-backend:latest

      # Build and push frontend image
      - name: Build frontend image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/chatbot-frontend:latest ./frontend

      - name: Push frontend image
        run: docker push ghcr.io/${{ github.repository_owner }}/chatbot-frontend:latest

  deploy:
    needs: dockerize
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy backend to Azure WebApp
        uses: azure/webapps-container-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_BACKEND }}
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          docker-custom-image-name: "ghcr.io/${{ github.repository_owner }}/chatbot-backend:latest"

      - name: Deploy frontend to Azure WebApp
        uses: azure/webapps-container-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_FRONTEND }}
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          docker-custom-image-name: "ghcr.io/${{ github.repository_owner }}/chatbot-frontend:latest"